repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.23.1 # replace with current version
    hooks:
      - id: pyproject2conda-yaml
        args: ["--pyproject", "pyproject.toml", "-c", "conda-forge", "-o", "dev-environment.yml", "-n", "snicarfx-dev", "-e", "dev", "-w", "check"]
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.23.1 # replace with current version
    hooks:
      - id: pyproject2conda-yaml
        args: ["--pyproject", "pyproject.toml", "-c", "conda-forge", "-o", "environment.yml", "-n", "snicarfx", "-w", "check"]
