repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.23.1 
    hooks:
      - id: pyproject2conda-yaml
        description:
          "Update dev-environment.yml if different dependencies than in pyproject.toml"
        args: ["--pyproject", "pyproject.toml", "-c", "conda-forge", "-o", "dev-environment.yml", "-n", "snicarfx-dev", "-g", "dev", "-w", "check", "--custom-command", "pre-commit # see .pre-commit-config.yaml for command details"]
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.23.1 
    hooks:
      - id: pyproject2conda-yaml
        description:
          "Update environment.yml if different dependencies than in pyproject.toml"
        args: ["--pyproject", "pyproject.toml", "-c", "conda-forge", "-o", "environment.yml", "-n", "snicarfx", "-w", "check", "--custom-command", "pre-commit # see .pre-commit-config.yaml for command details"]
