name: snicarfx

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python>=3.10
  - pandas>=2.2.0,<3.0
  - matplotlib>=3.10,<4.0
  - netCDF4>=1.7,<2.0
  - scipy>=1.11,<2.0
  - xarray>=2024.0.0,<2025.0.0
  - pyyaml>=6.0,<7.0
  - pydantic>=2.10,<3.0
  - PythonicDISORT>=1.6
  - pip
