[tool.poetry]
name = "snicar-fx"
version = "0.0.0"
description = ""
authors = ["snicar-fx team"]

[tool.poetry.dependencies]
python = ">=3.10"
pandas = "^2.3.0"
matplotlib = "^3.10"
netCDF4 = "^1.7"
scipy = "^1.11"
xarray = "^0.23.1"
pyyaml = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

