[tool.poetry]
name = "snicar-fx"
version = "0.0.0"
description = ""
authors = ["snicar-fx team"]

[tool.poetry.dependencies]
python = ">=3.8"
pandas = "^2.3.0"
matplotlib = "^3.10"
netCDF4 = "^1.7"
scipy = "^1.15"
xarray = "^2025.06"
pytest = "^8.4"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

