[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snicarfx"
version = "0.1.0"
description = "Radiative transfer modelling in the snow/ice-atmopshere coupled system"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "snicar-fx team", email = "openosmia@proton.me"} 
]
license = "ACSL"
license-files = ["LICENSE"]
keywords = ["snow", "albedo", "radiative-transfer", "ice", "atmosphere"]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3"
]

dependencies = [
    "pandas>=2.2.0,<3.0.0",
    "matplotlib>=3.10,<4.0.0",
    "netCDF4>=1.7,<2.0.0",
    "scipy>=1.11,<2.0.0",
    "xarray>=2024.0.0,<2025.0.0",
    "pyyaml>=6.0,<7.0.0",
    "pydantic>=2.10",
    "PythonicDISORT==1.7",
    "pooch[progress]>=1.8",
]

[project.optional-dependencies]
dev = [ 
    "pytest>=9.0,<10.0",
    "pytest-xdist>=3.8",
    "pytest-cov>=7",
    "ruff>=0.15",
    "pre-commit>=4.2"
]

[project.scripts]
snicarfx-download-data = "snicarfx.cli.download:main"

[project.urls]
Homepage = "https://github.com/openosmia/snicar-fx"
Issues = "https://github.com/openosmia/snicar-fx/issues"

[tool.ruff]
target-version = "py310"	
lint.select = [
    "E", "F", "I", "N", "B", "UP", "C4", "SIM", "PERF", "RUF", "ARG", "DTZ", "PIE", "TCH"
]
lint.ignore = [
    "B008",
    "SIM105",
]
lint.fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["snicarfx"]
combine-as-imports = true
force-single-line = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
